[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/brnovais/nvim-config.git"
    refreshPeriod = "24h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "24h"
